# Mod Properties
mod_id=thermal_foundation
mod_name=Thermal Foundation
mod_version=11.0.7

# Platform Properties
java_version=21
mc_version=1.21.1
neo_version=21.1.248

# Dependency Properties
cofh_core_version=11.0.2
cofh_core_max_version=11.1.0

thermal_core_version=11.0.7
thermal_core_max_version=11.1.0

jei_version=19.43.0.395

# Publishing Properties

# Options: alpha, beta, release
release_type=release